---
- name: 0.系统初始化
  gather_facts: false
  hosts: 
    - M22
  roles:
    - common
  tags: common

- name: 更新代码
  gather_facts: false
  hosts:
    - test
  roles:
    - git
  tags: git

- name: 安装zabbix_agent客户端
  hosts:
    - elk
  roles:
    - zabbix_agent
  tags: zabbix_agent

- name: 安装nginx
  gather_facts: false
  hosts:
    - test
  roles:
    - nginx
  tags: nginx

- name: 安装php
  gather_facts: false
  hosts:
    - test
  roles:
    - php
  tags: php

- name: 安装jdk
  gather_facts: false
  hosts:
    - test
  roles:
    - jdk
  tags: jdk

- name: 安装mysql
  gather_facts: false
  hosts:
    - test
  roles:
    - mysql
  tags: mysql
