---
- name: 安装常用软件包
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - telnet
    - vim
    - ntpdate

#- name: 关闭firewalld
#  service: name=firewalld state=stopped enabled=no

#- name: 关闭selinux
#  lineinfile:
#    dest: /etc/selinux/config
#    regexp: "^SELINUX="
#    line: "SELINUX=disabled"

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 同步系统时间
  shell: ntpdate ntp1.aliyun.com

- name: 添加定时任务
  cron: name=sync_time minute="*/5" job="/sbin/ntpdate ntp1.aliyun.com >/dev/null 2>&1" state=present
  ignore_errors: True

- name: 分发.bashrc
  copy: src=.bashrc dest=/root/.bashrc mode=644 owner=root group=root
  notify:
    - load global env

- name: 分发sysctl.conf
  copy: src=sysctl.conf dest=/etc/sysctl.conf mode=644 owner=root group=root
  notify:
    - sysctl effective

- name: 分发limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf mode=644 owner=root group=root

- name: 分发sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode=600 owner=root group=root
  notify:
    - restart sshd

- name: 分发sudoers
  copy: src=sudoers dest=/etc/sudoers mode=440 owner=root group=root

- name: 分发hosts.allow与hosts.deny
  copy: src={{ item }}  dest=/etc/{{ item }} mode=644 owner=root group=root
  with_items:
    - hosts.allow
    - hosts.deny

- name: 创建tomcat用户
  user: name=tomcat state=present
  ignore_errors: True
  register: result
  
- name: 为tomcat用户设置密码
  shell: echo YS1cj21KfB2 | passwd --stdin tomcat 
 # when: result|success

#- name: 修改主机名-centos7
#  shell: echo {{hostname|quote}} > /etc/hostname && \
#         hostnamectl set-hostname  {{hostname|quote}}

#- name: 一键添加到hosts
#  template: src=hosts.j2 dest=/etc/hosts
