---
- name: 安装依赖
  shell: yum -y install vim gcc gcc-c++ autoconf libjpeg libjpeg-devel libpng libpng-develfreetype freetype-devel libxml2 libxml2-devel zlib zlib-devel glibc glibc-develglib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devele2fsprogs e2fsprogs-devel krb5 krb5-devel libidn libidn-devel opensslopenssl-devel openldap openldap-devel nss_ldap openldap-clientsopenldap-servers curl-devel libevent libevent-devel openssl-devel unixODBC unixODBC-devel python-devel libtool-ltdl.x86_64 libtool-ltdl-devel.x86_64 libjpeg-devel libpng-devel freetype-devel -y
  ignore_errors: True

- name: 分发解压php包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "/opt/soft/php-*.tar.gz"

- name: useradd user
  user: name=nginx state=present
  ignore_errors: True

- name: 预编译php
  shell: cd  /tmp/php-* && \
         ./configure --prefix={{ php_dir }} --with-config-file-path={{ php_dir }}/etc --with-fpm-user=nginx --with-fpm-group=nginx --enable-fpm --enable-session --with-curl --with-openssl --with-gd --with-jpeg-dir --with-png-dir --with-freetype-dir --with-pdo-mysql=mysqlnd --without-pdo-sqlite --without-sqlite3 --disable-fileinfo 
  register: a_status
#- debug: var=a_status.stdout_lines
- debug: var=a_status.stdout_lines 
 
- name: 编译php
  shell: cd /tmp/php-* && \
         make
  register: b_status
#- debug: var=b_status.stdout_lines
- debug: var=b_status.stdout_lines 

- name: 安装php
  shell: cd /tmp/php-* && \
         make install
  register: c_status
#- debug: var=c_status.stdout_lines
- debug: var=c_status.stdout_lines 

- name: 生成php-fpm.conf
  shell: cd {{ php_dir }}/etc && \
         cp -rf php-fpm.conf.default php-fpm.conf

- name: 生成www.conf
  shell: cd {{ php_dir }}/etc/php-fpm.d && \
         cp -rf www.conf.default www.conf

- name: 生成php-fpm
  shell: cp -rf /tmp/php-*/sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm && \
         chmod +x /etc/init.d/php-fpm && \
         chkconfig --add /etc/init.d/php-fpm

- name: 停止php-fpm
  shell: pkill php-fpm
  ignore_errors: True  

- name: 启动php-fpm
  shell: /etc/init.d/php-fpm start
  register: php_status
- debug: var=php_status.stdout_lines

- name: check php variable 
  shell: cat /etc/profile
  register: result

- name: 配置php环境变量
  shell: /bin/echo {{ item }} >> /etc/profile; source /etc/profile
  when: result.stdout.find('php') == -1
  with_items:
     - export PATH=\$PATH:{{ php_dir }}/bin 
